### ISSUE TITLE
Gnome::Glib failing t/Variant.t test

### ISSUE THREAD

**Issue by frithnanth** [MARTIMM/gnome-glib#1]
There's a wrong `use` statement in t/Variant.t:
```raku
use Gnome::N::N-GVariant;
```
I guess it should read:
```raku
use Gnome::Glib::N-GVariant;
```
With this patch the test works.

**Comment by MARTIMM** [comment]
Hi,
I've recently moved a few objects from Gnome::N to Gnome::Glib and you're right, I forgot to change that line. Thanks for pointing that out to me.
There are a few other things in Variant.pm6 I was working on, when that's finished the fix above will come with it (that would not take too long).

**Comment by MARTIMM** [comment]
Just pushed version 0.18.2 of **Gnome::Glib**. Will be available soon from CPAN and zef. Need perhaps zef update.

**Comment by frithnanth** [comment]
Thank you for your quick response. The installation of the new version was flawless.
